[2024-10-16T00:23:28.605+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2024-10-15T00:00:00+00:00 [queued]>
[2024-10-16T00:23:28.614+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2024-10-15T00:00:00+00:00 [queued]>
[2024-10-16T00:23:28.615+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-10-16T00:23:28.627+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2024-10-15 00:00:00+00:00
[2024-10-16T00:23:28.631+0000] {standard_task_runner.py:60} INFO - Started process 70 to run task
[2024-10-16T00:23:28.634+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'scheduled__2024-10-15T00:00:00+00:00', '--job-id', '27', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpmwney__h']
[2024-10-16T00:23:28.635+0000] {standard_task_runner.py:88} INFO - Job 27: Subtask stream_data_from_api
[2024-10-16T00:23:28.683+0000] {task_command.py:423} INFO - Running <TaskInstance: user_automation.stream_data_from_api scheduled__2024-10-15T00:00:00+00:00 [running]> on host 0b70451349c6
[2024-10-16T00:23:28.760+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-10-15T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-15T00:00:00+00:00'
[2024-10-16T00:23:28.763+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_dag.py", line 39, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-10-16T00:23:28.776+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20241015T000000, start_date=20241016T002328, end_date=20241016T002328
[2024-10-16T00:23:28.789+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 27 for task stream_data_from_api (No module named 'kafka'; 70)
[2024-10-16T00:23:28.807+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-16T00:23:28.824+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
