[2024-12-19T15:13:56.930+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2024-12-19T15:13:55.634081+00:00 [queued]>
[2024-12-19T15:13:56.939+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2024-12-19T15:13:55.634081+00:00 [queued]>
[2024-12-19T15:13:56.940+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-12-19T15:13:56.953+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2024-12-19 15:13:55.634081+00:00
[2024-12-19T15:13:56.959+0000] {standard_task_runner.py:60} INFO - Started process 185 to run task
[2024-12-19T15:13:56.961+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'manual__2024-12-19T15:13:55.634081+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/kafka_streaming.py', '--cfg-path', '/tmp/tmpwppz2wne']
[2024-12-19T15:13:56.963+0000] {standard_task_runner.py:88} INFO - Job 12: Subtask stream_data_from_api
[2024-12-19T15:13:57.011+0000] {task_command.py:423} INFO - Running <TaskInstance: user_automation.stream_data_from_api manual__2024-12-19T15:13:55.634081+00:00 [running]> on host 4f6e27f3adf3
[2024-12-19T15:13:57.081+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-12-19T15:13:55.634081+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-19T15:13:55.634081+00:00'
[2024-12-19T15:13:57.084+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_streaming.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-12-19T15:13:57.096+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20241219T151355, start_date=20241219T151356, end_date=20241219T151357
[2024-12-19T15:13:57.107+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 12 for task stream_data_from_api (No module named 'kafka'; 185)
[2024-12-19T15:13:57.134+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-19T15:13:57.158+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
