[2024-10-15T06:10:56.387+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-15T06:10:56.397+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2024-10-14T00:00:00+00:00 [queued]>
[2024-10-15T06:10:56.398+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-10-15T06:10:56.412+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2024-10-14 00:00:00+00:00
[2024-10-15T06:10:56.416+0000] {standard_task_runner.py:60} INFO - Started process 70 to run task
[2024-10-15T06:10:56.421+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'scheduled__2024-10-14T00:00:00+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpc389lp9y']
[2024-10-15T06:10:56.423+0000] {standard_task_runner.py:88} INFO - Job 16: Subtask stream_data_from_api
[2024-10-15T06:10:56.475+0000] {task_command.py:423} INFO - Running <TaskInstance: user_automation.stream_data_from_api scheduled__2024-10-14T00:00:00+00:00 [running]> on host 5644afbf65e2
[2024-10-15T06:10:56.544+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-10-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-14T00:00:00+00:00'
[2024-10-15T06:11:00.036+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-15T06:11:00.037+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2024-10-15T06:11:00.037+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-15T06:11:03.325+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-15T06:11:03.326+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2024-10-15T06:11:03.328+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_dag.py", line 43, in stream_data
    producer = KafkaProducer(bootstrap_servers=['broker:29092'], max_block_ms=5000)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-10-15T06:11:03.344+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20241014T000000, start_date=20241015T061056, end_date=20241015T061103
[2024-10-15T06:11:03.357+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 16 for task stream_data_from_api (NoBrokersAvailable; 70)
[2024-10-15T06:11:03.387+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-15T06:11:03.400+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
