[2024-12-21T06:28:05.574+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2024-12-21T06:28:04.380305+00:00 [queued]>
[2024-12-21T06:28:05.583+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2024-12-21T06:28:04.380305+00:00 [queued]>
[2024-12-21T06:28:05.584+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-12-21T06:28:05.598+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2024-12-21 06:28:04.380305+00:00
[2024-12-21T06:28:05.605+0000] {standard_task_runner.py:60} INFO - Started process 508 to run task
[2024-12-21T06:28:05.608+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'manual__2024-12-21T06:28:04.380305+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/kafka_streaming.py', '--cfg-path', '/tmp/tmpyw2t30fq']
[2024-12-21T06:28:05.609+0000] {standard_task_runner.py:88} INFO - Job 30: Subtask stream_data_from_api
[2024-12-21T06:28:05.655+0000] {task_command.py:423} INFO - Running <TaskInstance: user_automation.stream_data_from_api manual__2024-12-21T06:28:04.380305+00:00 [running]> on host f6efe59a6eda
[2024-12-21T06:28:05.733+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-12-21T06:28:04.380305+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-21T06:28:04.380305+00:00'
[2024-12-21T06:28:06.847+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-12-21T06:28:06.847+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2024-12-21T06:28:06.848+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-12-21T06:28:07.869+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-12-21T06:28:07.870+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2024-12-21T06:28:07.871+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_streaming.py", line 46, in stream_data
    producer = KafkaProducer(bootstrap_servers=['broker:29092'], max_block_ms=5000)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-12-21T06:28:07.887+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20241221T062804, start_date=20241221T062805, end_date=20241221T062807
[2024-12-21T06:28:07.899+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 30 for task stream_data_from_api (NoBrokersAvailable; 508)
[2024-12-21T06:28:07.912+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-21T06:28:07.927+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
