[2024-12-19T15:07:36.652+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2024-12-19T15:07:35.161404+00:00 [queued]>
[2024-12-19T15:07:36.661+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api manual__2024-12-19T15:07:35.161404+00:00 [queued]>
[2024-12-19T15:07:36.662+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-12-19T15:07:36.677+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2024-12-19 15:07:35.161404+00:00
[2024-12-19T15:07:36.684+0000] {standard_task_runner.py:60} INFO - Started process 94 to run task
[2024-12-19T15:07:36.686+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'manual__2024-12-19T15:07:35.161404+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/kafka_streaming.py', '--cfg-path', '/tmp/tmptlxwu_gc']
[2024-12-19T15:07:36.688+0000] {standard_task_runner.py:88} INFO - Job 11: Subtask stream_data_from_api
[2024-12-19T15:07:36.741+0000] {task_command.py:423} INFO - Running <TaskInstance: user_automation.stream_data_from_api manual__2024-12-19T15:07:35.161404+00:00 [running]> on host 4f6e27f3adf3
[2024-12-19T15:07:36.818+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-12-19T15:07:35.161404+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-19T15:07:35.161404+00:00'
[2024-12-19T15:07:36.821+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/kafka_streaming.py", line 41, in stream_data
    from kafka import KafkaProducer
ModuleNotFoundError: No module named 'kafka'
[2024-12-19T15:07:36.836+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20241219T150735, start_date=20241219T150736, end_date=20241219T150736
[2024-12-19T15:07:36.852+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 11 for task stream_data_from_api (No module named 'kafka'; 94)
[2024-12-19T15:07:36.899+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-12-19T15:07:36.916+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
