[2024-10-27T10:29:40.099+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-27T10:29:40.109+0000] {taskinstance.py:1979} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: user_automation.stream_data_from_api scheduled__2024-10-21T00:00:00+00:00 [queued]>
[2024-10-27T10:29:40.110+0000] {taskinstance.py:2193} INFO - Starting attempt 1 of 1
[2024-10-27T10:29:40.125+0000] {taskinstance.py:2217} INFO - Executing <Task(PythonOperator): stream_data_from_api> on 2024-10-21 00:00:00+00:00
[2024-10-27T10:29:40.130+0000] {standard_task_runner.py:60} INFO - Started process 71 to run task
[2024-10-27T10:29:40.139+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'user_automation', 'stream_data_from_api', 'scheduled__2024-10-21T00:00:00+00:00', '--job-id', '64', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmpx4awmmey']
[2024-10-27T10:29:40.140+0000] {standard_task_runner.py:88} INFO - Job 64: Subtask stream_data_from_api
[2024-10-27T10:29:40.193+0000] {task_command.py:423} INFO - Running <TaskInstance: user_automation.stream_data_from_api scheduled__2024-10-21T00:00:00+00:00 [running]> on host 5e2d829f4d1d
[2024-10-27T10:29:40.276+0000] {taskinstance.py:2513} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airscholar' AIRFLOW_CTX_DAG_ID='user_automation' AIRFLOW_CTX_TASK_ID='stream_data_from_api' AIRFLOW_CTX_EXECUTION_DATE='2024-10-21T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-21T00:00:00+00:00'
[2024-10-27T10:29:43.940+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-27T10:29:43.941+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2024-10-27T10:29:43.942+0000] {conn.py:1205} INFO - Probing node bootstrap-0 broker version
[2024-10-27T10:29:47.233+0000] {conn.py:1527} WARNING - DNS lookup failed for broker:29092, exception was [Errno -2] Name or service not known. Is your advertised.listeners (called advertised.host.name before Kafka 9) correct and resolvable?
[2024-10-27T10:29:47.234+0000] {conn.py:315} ERROR - DNS lookup failed for broker:29092 (0)
[2024-10-27T10:29:47.235+0000] {taskinstance.py:2731} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 444, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 414, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 200, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 217, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/my_dag.py", line 45, in stream_data
    producer = KafkaProducer(bootstrap_servers=['broker:29092'], max_block_ms=5000)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/producer/kafka.py", line 381, in __init__
    client = KafkaClient(metrics=self._metrics, metric_group_prefix='producer',
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 244, in __init__
    self.config['api_version'] = self.check_version(timeout=check_timeout)
  File "/home/airflow/.local/lib/python3.8/site-packages/kafka/client_async.py", line 927, in check_version
    raise Errors.NoBrokersAvailable()
kafka.errors.NoBrokersAvailable: NoBrokersAvailable
[2024-10-27T10:29:47.247+0000] {taskinstance.py:1149} INFO - Marking task as FAILED. dag_id=user_automation, task_id=stream_data_from_api, execution_date=20241021T000000, start_date=20241027T102940, end_date=20241027T102947
[2024-10-27T10:29:47.266+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 64 for task stream_data_from_api (NoBrokersAvailable; 71)
[2024-10-27T10:29:47.298+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-10-27T10:29:47.311+0000] {taskinstance.py:3312} INFO - 0 downstream tasks scheduled from follow-on schedule check
