[2024-12-21T06:39:51.427+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: user_automation.stream_data_from_api manual__2024-12-21T06:39:14.930091+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
